version: 1

# Build the main gawamango binary
# goos and goarch must be single strings, not arrays
goos: linux
goarch: amd64

env:
  - CGO_ENABLED=0

# Binary name will be gawamango
binary: gawamango

# Main directory for the build
dir: .

# Root main.go file to build
main: ./cmd/gawamango/main.go

# LDFLAGS to pass to the Go compiler - use direct value
ldflags: 
  - "-s -w -X github.com/ringsaturn/gawamango/internal/proxy.Version=${VERSION}"

# Ensure binary is built with Go modules
goproxy: https://proxy.golang.org

# Build with -trimpath
flags:
  - -trimpath 