// Code generated by "stringer -type OpCode internal/protocol/header.go"; DO NOT EDIT.

package protocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OP_COMPRESSED-2012]
	_ = x[OP_MSG-2013]
}

const _OpCode_name = "OP_COMPRESSEDOP_MSG"

var _OpCode_index = [...]uint8{0, 13, 19}

func (i OpCode) String() string {
	i -= 2012
	if i < 0 || i >= OpCode(len(_OpCode_index)-1) {
		return "OpCode(" + strconv.FormatInt(int64(i+2012), 10) + ")"
	}
	return _OpCode_name[_OpCode_index[i]:_OpCode_index[i+1]]
}
