name: SLSA Go Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions: read-all

jobs:
  # Generate ldflags dynamically.
  args:
    runs-on: ubuntu-latest
    outputs:
      commit-date: ${{ steps.ldflags.outputs.commit-date }}
      commit: ${{ steps.ldflags.outputs.commit }}
      version: ${{ steps.ldflags.outputs.version }}
      tree-state: ${{ steps.ldflags.outputs.tree-state }}
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: ldflags
        run: |
          echo "commit-date=$(git log --date=iso8601-strict -1 --pretty=%ct)" >> "$GITHUB_OUTPUT"
          echo "commit=$GITHUB_SHA" >> "$GITHUB_OUTPUT"
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"
          echo "tree-state=$(if git diff --quiet; then echo "clean"; else echo "dirty"; fi)" >> "$GITHUB_OUTPUT"

  # SLSA builder as a reusable workflow
  build:
    needs: [args]
    permissions:
      id-token: write  # For SLSA provenance
      contents: write  # For creating releases
      actions: read    # For workflow access
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v2.1.0
    with:
      go-version: '1.24'
      evaluated-envs: |
        {
          "COMMIT_DATE": "${{ needs.args.outputs.commit-date }}",
          "COMMIT": "${{ needs.args.outputs.commit }}",
          "VERSION": "${{ needs.args.outputs.version }}",
          "TREE_STATE": "${{ needs.args.outputs.tree-state }}",
          "LDFLAGS": "-s -w -X github.com/ringsaturn/gawamango/internal/proxy.Version=${{ needs.args.outputs.version }}"
        }
      prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
